image: ruby:latest

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs npm
  - node -v && npm -v

pages:
  script:
    - bundle install
    - npm ci
    - bundle exec middleman build --verbose
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
