image: ruby:latest

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs npm
  - node -v && npm -v

pages:
  script:
    - npm ci
    - gem install bundler:1.17.3
    - bundle install
    - bundle exec middleman build --verbose
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
