name: Github Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '13'

    - name: Install Chrome
      run: |
        sudo apt-get install libxss1 libappindicator1 libindicator7	
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb	
        sudo apt install ./google-chrome*.deb
    
    - name: Bridgetown Setup
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --quiet
        npm install -g yarn --silent
        yarn install --silent
    
    - name: Bridgetown Build
      run: |
        BRIDGETOWN_ENV=production NODE_ENV=production yarn webpack-build && yarn build
    
    - name: Bridgetown Deploy (Push to Github Pages)
      run: |
        cd ./output
        git init
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        git commit -m "deploy site"
        git push --force "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:gh-pages
